version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: portfolio_mysql
    environment:
      MYSQL_DATABASE: "portfolio"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: